# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redtree_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('confidence', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('type_index', models.TextField(blank=True, null=True)),
                ('internal_data', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('severity', models.TextField(blank=True, null=True)),
                ('virtue_id', models.IntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('date_confirmed', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Application Scan Result',
            },
        ),
        migrations.CreateModel(
            name='ApplicationScans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('scan_id', models.TextField(blank=True, null=True)),
                ('status_uri', models.TextField(blank=True, null=True)),
                ('scan_status', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redtree_app.Applications')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Application Scans',
            },
        ),
        migrations.CreateModel(
            name='BurpEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_evidence', to='playground.ApplicationScanData')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Burp Evidence',
            },
        ),
        migrations.CreateModel(
            name='SshyzeCiphers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ciphers', models.CharField(blank=True, max_length=500, null=True)),
                ('host', models.CharField(blank=True, max_length=500, null=True)),
                ('port', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Sshyze Ciphers',
            },
        ),
        migrations.CreateModel(
            name='SshyzeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Sshyze Type',
            },
        ),
        migrations.AddField(
            model_name='sshyzeciphers',
            name='cipher_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sshyze_ciphers', to='playground.SshyzeType'),
        ),
        migrations.AddField(
            model_name='applicationscandata',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.ApplicationScans'),
        ),
        migrations.AddField(
            model_name='applicationscandata',
            name='application_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redtree_app.Applications'),
        ),
    ]
