# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshyzeciphers',
            options={'verbose_name_plural': 'Sshyze Ciphers'},
        ),
    ]
