# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-19 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20191017_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscandata',
            name='severity',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
