# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-25 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20191119_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscandata',
            name='application_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_scans', to='redtree_app.Applications'),
        ),
    ]
