# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-21 12:26
from __future__ import unicode_literals

from django.db import migrations


def create_network(apps, schema_editor):
	Networks = apps.get_model('redtree_app', 'Networks')
	if Networks.objects.all().count() == 0:
		Networks.objects.create(
			network='External Network',
			network_type='External'
		)

class Migration(migrations.Migration):

	dependencies = [
		('redtree_app', '0001_initial'),
	]

	operations = [
		migrations.RunPython(create_network),
	]
