# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-11 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0003_vulnerability_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvulnerabilities',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
