# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0005_applicationvulnerability_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmicroservicecloudstorage',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicednsenum',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicemasscan',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicenessus',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicescreenshot',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicesshyze',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicesslyze',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logmicroservicewhois',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
