# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0006_auto_20190919_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmicroserviceburp',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmicroservicecloudstorage',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmicroservicednsenum',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmicroservicescreenshot',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmicroservicesshyze',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmicroservicesslyze',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmicroservicewhois',
            name='network_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logmicroserviceburp',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
