# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-26 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0007_auto_20190920_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nessusdata',
            name='last_seen',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
