# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0008_auto_20190925_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='host_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_applications', to='redtree_app.Host'),
        ),
        migrations.AddField(
            model_name='nessusdata',
            name='host_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_issues', to='redtree_app.Host'),
        ),
    ]
