# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-02 10:45
from __future__ import unicode_literals

from django.db import migrations


def update_nessus_host_link(apps, schema_editor):
	NessusData = apps.get_model('redtree_app', 'NessusData')
	Host = apps.get_model('redtree_app', 'Host')
	nessus_objs = NessusData.objects.all()
	for nessus_obj in nessus_objs:
		if nessus_obj.host and not nessus_obj.host_link:
			host = nessus_obj.host
			try:
				host_obj = Host.objects.get(host=host)
			except Host.DoesNotExist:
				host_obj = Host.objects.create(
					host=host,
					user_host=nessus_obj.user_host
				)
			except Host.MultipleObjectsReturned:
				host_obj = Host.objects.filter(host=host).first()
			nessus_obj.host_link = host_obj
			nessus_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0009_auto_20191002_0538'),
    ]

    operations = [
    	migrations.RunPython(update_nessus_host_link),
    ]
