# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0011_nessusdata_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SslyzeCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=128, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('verified_certificate_chain', models.BooleanField(default=False)),
                ('has_sha1_in_certificate_chain', models.BooleanField(default=False)),
                ('subject', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'sslyze_certificates',
            },
        ),
    ]
