# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0013_auto_20191011_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslyzecertificates',
            name='common_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
