# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 04:55
from __future__ import unicode_literals

from django.db import migrations


def update_certificate_common_name(apps, schema_editor):
	SslyzeCertificates = apps.get_model('redtree_app', 'SslyzeCertificates')
	certificate_objs = SslyzeCertificates.objects.all()
	for certificate_obj in certificate_objs:
		subject = certificate_obj.subject
		if subject:
			subject_list = subject.split(", ")
			search_text = "commonName"
			common_name_list = list(filter(lambda x: search_text in x, subject_list))
			try:
				common_name = common_name_list[0][11:]
			except:
				common_name = None
			if common_name and not certificate_obj.common_name:
				certificate_obj.common_name = common_name
				certificate_obj.save()


class Migration(migrations.Migration):

	dependencies = [
		('redtree_app', '0014_sslyzecertificates_common_name'),
	]

	operations = [
		migrations.RunPython(update_certificate_common_name),
	]
