# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-31 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0015_update_sslyze_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessusfile',
            name='applications_process_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nessusfile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nessusfile',
            name='vulnerabilities_process_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nessusfile',
            name='xml_process_status',
            field=models.BooleanField(default=False),
        ),
    ]
