# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-31 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0016_auto_20191031_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessusfile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
