# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-04 10:58
from __future__ import unicode_literals

from django.db import migrations
from datetime import date, datetime, timedelta
from django.utils import timezone

def update_next_scan(apps, schema_editor):
	ClientConfiguration = apps.get_model('redtree_app', 'ClientConfiguration')
	client_conf_obj = ClientConfiguration.objects.first()
	if client_conf_obj:
		scan_frequency = int(client_conf_obj.scan_frequency)
		date = datetime.now() + timedelta(days=scan_frequency)
		day = date.strftime('%A')
		client_conf_obj.next_scan = day
		client_conf_obj.last_scan = timezone.now()
		client_conf_obj.save()
	

class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0018_clientconfiguration_next_scan'),
    ]

    operations = [
    	migrations.RunPython(update_next_scan),
    ]
