# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0019_update_next_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfiguration',
            name='next_scan_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='last_scan',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
