# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0021_auto_20191105_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionCacheCiphers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cipher_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_decimal', models.CharField(blank=True, max_length=64, null=True)),
                ('id_hex', models.CharField(blank=True, max_length=64, null=True)),
                ('name_openssl', models.CharField(blank=True, max_length=128, null=True)),
                ('name_iana', models.CharField(blank=True, max_length=128, null=True)),
                ('keyx', models.CharField(blank=True, max_length=64, null=True)),
                ('enc', models.CharField(blank=True, max_length=64, null=True)),
                ('bits', models.CharField(blank=True, max_length=64, null=True)),
                ('strength', models.CharField(blank=True, max_length=32, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('null', models.BooleanField(default=False)),
                ('export', models.BooleanField(default=False)),
                ('rc4', models.BooleanField(default=False)),
                ('cbc', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Encryption Cache Ciphers',
            },
        ),
        migrations.CreateModel(
            name='EncryptionCacheSsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ssh_cipher_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ssh_cipher', models.CharField(max_length=128, unique=True)),
                ('cipher_type', models.CharField(blank=True, max_length=64, null=True)),
                ('arc4', models.BooleanField(default=False)),
                ('cbc', models.BooleanField(default=False)),
                ('weak', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Encryption Cache Ssh',
            },
        ),
    ]
