# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0022_encryptioncacheciphers_encryptioncachessh'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphers',
            name='strength',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
