# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-12 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0023_ciphers_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslyzecertificates',
            name='algorithm',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
