# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-14 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0024_sslyzecertificates_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessusfile',
            name='hosts_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessusfile',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
