# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0025_auto_20191114_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudassetsdata',
            name='category',
            field=models.CharField(blank=True, choices=[('S3', 'S3'), ('GCP', 'GCP'), ('Azure', 'Azure')], default='S3', max_length=20, null=True),
        ),
    ]
