# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-25 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0028_applicationvulnerabilityriskdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationvulnerabilityriskdata',
            options={'verbose_name_plural': 'Application Vulnerability History'},
        ),
    ]
