# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0031_auto_20191127_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveVulnerabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('virtue_id', models.IntegerField(blank=True, null=True)),
                ('plugin_id', models.CharField(blank=True, max_length=500, null=True)),
                ('host_ip', models.CharField(blank=True, max_length=500, null=True)),
                ('port', models.CharField(blank=True, max_length=200, null=True)),
                ('risk', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('remediation', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('evidence', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('masscan_post_status', models.BooleanField(default=False)),
                ('network_type', models.CharField(blank=True, max_length=500, null=True)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_date', models.DateField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_vulnerabilities', to='redtree_app.Host')),
            ],
            options={
                'verbose_name_plural': 'Archived Vulnerabilities',
            },
        ),
    ]
