# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0032_archivevulnerabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('services', models.IntegerField(blank=True, default=0, null=True)),
                ('high_strength', models.IntegerField(blank=True, default=0, null=True)),
                ('medium_strength', models.IntegerField(blank=True, default=0, null=True)),
                ('low_strength', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Encryption History',
            },
        ),
    ]
