# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-03-04 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0034_activationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='port',
            field=models.CharField(max_length=200, null=True, blank=True, default=80),
        ),
    ]