# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0036_customernotificationemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsrdsendpoint',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awsrdsendpoint',
            name='scan_status',
            field=models.NullBooleanField(default=None),
        ),
    ]
