# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-14 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0038_auto_20200428_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerNotificationEmails',
        ),
    ]
