# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-15 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0039_delete_customernotificationemails'),
        ('redtree_app', '0038_applications_burp_scanning'),
    ]

    operations = [
    ]
