# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0040_merge_20200515_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='burp_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='screenshot_title',
            field=models.BooleanField(default=True),
        ),
    ]
