# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-18 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0040_merge_20200515_1052'),
        ('redtree_app', '0040_merge_20200515_0727'),
    ]

    operations = [
    ]
