# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0041_auto_20200611_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsapigateway',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awsapigateway',
            name='status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]