# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-12 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0041_auto_20200611_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='burp_title',
        ),
    ]
