# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-12 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0043_auto_20200612_0241'),
        ('redtree_app', '0042_add_apifields'),
    ]

    operations = [
    ]
