# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0044_merge_20200612_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsapigateway',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]