# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-16 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0045_awsapigateway_last_scan'),
        ('redtree_app', '0042_auto_20200611_0605'),
    ]

    operations = [
    ]
