# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-16 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtree_app', '0046_merge_20200615_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='burp_title',
        ),
    ]
