# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-31 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0002_applications_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 31, 12, 5, 44, 971155, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='scope',
            field=models.CharField(blank=True, choices=[('black', 'black'), ('grey', 'grey'), ('white', 'white')], default='black', max_length=20, null=True),
        ),
    ]
