# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0003_auto_20181231_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('network_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Appliances',
            },
        ),
    ]
