# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0004_appliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='redtree_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
