# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0005_appliances_redtree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
