# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-16 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import purpleleaf_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0006_host_ip_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='file_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='file',
            field=models.FileField(blank=True, upload_to="/"),
        ),
    ]
