# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0007_auto_20190116_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationvulnerabilities',
            name='host_ip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilities',
            name='host_ip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
