# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-25 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0009_activitylog'),
    ]

    operations = [
    ]