# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0011_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='networks',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
