# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-11 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0012_networks_network_type'),
    ]

    operations = [
    ]
