# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-11 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0013_update_network_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='issue_virtue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
