# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0014_notifications_issue_virtue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='issue_network_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
