# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-02 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleleaf_app', '0015_notifications_issue_network_type'),
    ]

    operations = []
