from django.conf.urls import url
from .views import *


urlpatterns = [
    url(
        r'^$',
        index,
        name='index'
    ),
    url(
        r'^home/$',
        home,
        name='home'
    ),
    url(
        r'^settings/$',
        setting,
        name='setting'
    ),
    url(
        r'^vulnerabilities/$',
        VulnerabilitiesDetailView.as_view(),
        name='vulnerabilities'
    ),
    url(
        r'^host/(?P<host_id>[0-9]+)/$',
        HostDetailView.as_view(),
        name="host_detail"
    ),
    url(
        r'^vulnerability/create/$',
        VulnerabilityCreateView.as_view(),
        name='create_vulnerability'
    ),
    url(
        r'^vulnerabilities/update/$',
        VulnerabilitiesUpdateView.as_view(),
        name='update_vulnerabilities'
    ),
    url(
        r'^vulnerabilities/edit/(?P<id>[0-9]+)/$',
        VulnerabilityUpdateView.as_view(),
        name='edit_vulnerabilities'
    ),
    url(
        r'^vulnerability-delete/(?P<id>[0-9]+)$',
        VulnerabilityDeleteView.as_view(),
        name='vulnerability_delete'
    ),
    url(
        r'^vulnerability/delete/(?P<virtue_id>[0-9]+)/$',
        VulnerabilitiesDeleteView.as_view(),
        name='delete_vulnerability'
    ),
    url(
        r'^logs/purpleleaf/$',
        PurpleleafAuditLogsView.as_view(),
        name='purpleleaf_audit_logs_view'
    ),
    url(
        r'^logs/redtree/$',
        RedtreeAuditLogsView.as_view(),
        name='redtree_audit_logs_view'
    ),
    url(
        r'^vulnerabilities/(?P<id>[0-9]+)/$',
        VulnerabilityHostDetailView.as_view(),
        name='vulnerability_host_detail'
    ),
    url(
        r'^vulnerability/application/$',
        create_application_vulnerability,
        name='create_application_vulnerability'
    ),
    url(
        r'^vulnerabilities/external/(?P<virtue_id>[0-9]+)/$',
        VulnerabilityDetailView.as_view(),
        name='external_vulnerability_detail'
    ),
    url(
        r'^vulnerabilities/internal/(?P<virtue_id>[0-9]+)/$',
        VulnerabilityDetailView.as_view(),
        name='internal_vulnerability_detail'
    ),
    url(
        r'^vulnerabilities/host/(?P<host_id>[0-9]+)/$',
        vulnerability_host,
        name='vulnerability_host'
    ),
    url(
        r'^vulnerabilities/host/(?P<host_id>[0-9]+)/(?P<virtue_id>[0-9]+)/$',
        vulnerabilities_host_detail,
        name='vulnerabilities_host_detail'
    ),
    url(
        r'^report/$',
        report,
        name='report'
    ),
    url(
        r'^report/details/$',
        report_details,
        name='report_details'
    ),
    url(
        r'^report/pdf/$',
        report_pdf.as_view(),
        name='report_pdf'
    ),
    url(
        r'^retest/$',
        RetestVulnerabilitiesView.as_view(),
        name='retest_vulnerabilities'
    ),
    url(
        r'^notifications$',
        notifications,
        name='notifications'
    ),
    url(
        r'^scanningstatus$',
        scanningstatus,
        name='scanningstatus'
    ),
    url(
        r'^user-delete/(?P<id>[0-9]+)/$',
        user_delete,
        name='user_delete'
    ),
    url(
        r'^data/iptrackinfo/',
        ipinfodata,
        name="iptrackinfo"
    ),
    url(
        r'^notification/email-delete/(?P<email_id>[0-9]+)/$',
        delete_notification_email,
        name='delete_notification_email'
    ),
    url(
        r'^report/all-reports/$',
        show_all_reports,
        name="show_all_reports"
    ),
    url(
        r'^delete-report/(?P<file_id>[0-9]+)$',
        delete_report,
        name="delete_reports"
    ),
    url(
        r'^retest-history$',
        retest_history,
        name="retest_history"
    ),
    url(
        r'^event-history$',
        event_history,
        name="event_history"
    ),
    url(
        r'^vulnerabilities/network/(?P<network_id>[0-9]+)/$',
        network_vulnerabilities_detail,
        name='network_vulnerabilities_detail'
    ),
    url(
        r'^vulnerabilities/network/(?P<network_id>[0-9]+)/(?P<virtue_id>[0-9]+)/$',
        vulnerability_network_detail,
        name='vulnerability_network_detail'
    ),
    url(
        r'^add-user$',
        add_user,
        name="add_user"
    ),
    url(
        r'^edit-user$',
        edit_user,
        name="edit_user"
    ),
    url(
        r'^user-login$',
        user_login,
        name="user_login"
    ),
    url(
        r'^user-logout$',
        user_logout,
        name="user_logout"
    ),
    url(
        r'^redtree-error-log$',
        redtree_errors_log,
        name="redtree_error_history"
    ),
    url(
        r'^configuration-export/$',
        export_configuration_json,
        name='export_configuration_json'
    ),
    url(
        r'^burp/$',
        burpdata,
        name="burpdata"
    ),
    url(
        r'^burp/reprocess/$',
        process_burp_data,
        name="burp_reprocess"
    ),
    url(
        r'^burp/clear-burp-data/$',
        clear_burp_data,
        name="clear_burp_data"
    ),
    url(
        r'^vulnerabilites-detail$',
        vulnerabilities_detail,
        name="vulnerabilities_detail"
    ),
    url(
        r'^autocomplete-hosts$',
        all_hosts_record,
        name='all_hosts_record'
    ),
    url(
        r'^queue/$',
        testing_queue,
        name='testing_queue'
    ),
    url(
        r'^queue/(?P<id>[0-9]+)/$',
        queue_vulnerability,
        name='test_vulnerability'
    ),
    url(
        r'^queue/(?P<virtue_id>[0-9]+)/(?P<id>[0-9]+)$',
        queue_vulnerability_host_detail,
        name='test_vulnerability_host_detail'
    ),
    url(
        r'^queue-vulnerability-delete/(?P<virtue_id>[0-9]+)/(?P<id>[0-9]+)/$',
        queue_vulnerabilty_delete,
        name='queue-delete'
    ),
    url(
        r'^queue/(?P<virtue_id>[0-9]+)/(?P<id>[0-9]+)/edit$',
        queue_vulnerability_edit,
        name='queue_vulnerability_edit'
    ),
    url(
        r'^queue/(?P<id>[0-9]+)/approve$',
        approve_testvulnerability,
        name='approve_testvulnerability'
    ),
    url(
        r'^cipher/(?P<cipher>[\w-]+)/',
        cipher_detail,
        name ='cipher_detail'
    ),
    url(
        r'^encryption/$',
        encryption,
        name='encryption'
    ),
    url(
        r'^encryption/update$',
        cipher_update,
        name='cipher_update'
    ),
    url(
        r'^encryption/definitions$',
        EncryptionDefinitionDetailView.as_view(),
        name='encryption_definition_detail'
    ),
    url(
        r'^encryption/definitions/ssh$',
        EncryptionSshDefinitionDetailView.as_view(),
        name='encryption_ssh_definition_detail'
    ),
    url(
        r'^encryption/definitions/ciphers/update$',
        encryption_definition_cipher_update,
        name='encryption_definition_cipher_update'
    ),
    url(
        r'^encryption/definitions/ssh/update$',
        encryption_definition_ssh_update,
        name='encryption_definition_ssh_update'
    ),
    url(
        r'^encryption/proto/(?P<protocol>\w+)/$',
        EncryptionProtocolDetailView.as_view(),
        name ='encryption_detail'
    ),
    url(
        r'^applications/$',
        ApplicationsDetailView.as_view(),
        name='applications'
    ),
    url(
        r'^applications/(?P<application_id>[0-9]+)/toggle_active/$',
        update_application_status_view,
        name='update_application_scan_status'
    ),
    url(
        r'^burp/(?P<application_id>[0-9]+)/burp_toggle_active/$',
        burp_update_application_status_view,
        name='burp_update_application_scan_status'
    ),
    url(
        r'^log-hours/$',
        log_hours,
        name='log_hours'
    ),
    url(
        r'^fetch-application-urls/$',
        fetch_application_urls,
        name="fetch_application_urls"
    ),
    url(
        r'^appliances-delete/(?P<appliance_id>[0-9]+)$',
        appliances_delete,
        name='appliances_delete'
    ),
    url(
        r'^settings/appliance/(?P<appliance_id>[0-9]+)/$',
        appliance_setting,
        name='appliance_setting'
    ),
    url(
        r'^burp/(?P<type_index>\w+)/$',
        burp_detail_by_type_index,
        name='burp_detail_by_index'
    ),
    url(
        r'^burp/application/(?P<application_id>[0-9]+)/$',
        burp_issue_by_application_id,
        name='burp_issue_by_application_id'
    ),
    url(
        r'^burp/(?P<type_index>\w+)/(?P<burp_id>[0-9]+)/$',
        burp_issue_detail_by_id,
        name='burp_detail_by_id'
    ),
    url(
        r'^encryption/ssh/$',
        ssh_playground,
        name='ssh_playground'
    ),
    url(r'^encryption/ssh/(?P<type>[0-9A-Za-z-_]+)/(?P<cipher>[0-9A-Za-z-.@]+)/$',
        encryption_ssh_detail,
        name='ssh-encryption-detail'
    ),
    url(
        r'^domains/(?P<domain_id>[0-9]+)/$',
        domain_delete_view,
        name='detail_or_update_domains'
    ),
    url(
        r'^subdomains/(?P<domain_id>[0-9]+)/$',
        subdomain_delete_view,
        name='detail_or_update_subdomains'
    ),
    url(
        r'^charts/$',
        chart_data,
        name='chart-records'
    ),
    url(
        r'^ciphers/delete/$',
        cipher_delete,
        name='cipher_delete'
    ),
    url(
        r'^sshyze/delete/$',
        sshyze_ciphers_delete,
        name='sshyze_ciphers_delete'
    ),
    url(
        r'^subdomains/$',
        sub_domain_view,
        name='sub_domain'
    ),
    url(
        r'^application/(?P<application_id>[0-9]+)/$',
        application_detail,
        name='application_detail_view'
    ),
    url(
        r'^logs/$',
        logs_view,
        name='logs_view'
    ),
    url(
        r'^logs/microservices/$',
        microservices_audit_logs_view,
        name='microservices_audit_logs_view'
    ),
    url(
        r'^logs/microservices/nessus/$',
        microservices_nessus_logs_view,
        name='microservices_nessus_logs_view'
    ),
    url(
        r'^logs/microservices/masscan/$',
        MicroservicesMasscanLogsView.as_view(),
        name='microservices_masscan_logs_view'
    ),
    url(
        r'^logs/cloudstorage/$',
        microservices_cloudstorage_logs_view,
        name='microservices_cloudstorage_logs_view'
    ),
    url(
        r'^application/(?P<application_id>[0-9]+)/vulnerability/(?P<vul_id>[0-9]+)/$',
        application_vulnerability_detail_view,
        name='application_vulnerability_detail_view'
    ),
    url(
        r'^application-vulnerability/delete/(?P<id>[0-9]+)/$',
        delete_application_vulnerability,
        name='application_vulnerability_delete'
    ),
    url(
        r'^logs/dnsenum/$',
        dnsenum_logs_views,
        name='dnsenum_logs_views'
    ),
    url(
        r'^logs/burp/$',
        burp_logs,
        name='burp-logs'
    ),
    url(
        r'^logs/sslyze/$',
        sslyze_logs,
        name='sslyze-logs'
    ),
    url(
        r'^logs/sshyze/$',
        sshyze_logs,
        name='sshyze-logs'
    ),
    url(
        r'^logs/screenshot/$',
        screenshot_logs,
        name='screenshot-logs'
    ),
    url(
        r'^logs/whois/$',
        microservices_whois_logs,
        name='whois-logs'
    ),
    url(
        r'^burp/(?P<type_index>\w+)/application/(?P<application_scan_id>[0-9]+)/$',
        application_scan_detail_view,
        name='application_scan_detail_view'
    ),
    url(
        r'^cloud/$',
        cloud,
        name="cloud"
    ),
    url(
        r'^cloud/s3/(?P<cloud_asset_id>[0-9]+)/$',
        cloud_asset_detail,
        name="cloud_asset_detail"
    ),
    url(
        r'^whois-map/$',
        whois_map_details,
        name='whois-map-details'
    ),
    url(
        r'^subdomains/refresh/$',
        subdomain_refresh,
        name="subdomain-refresh"
    ),
    url(
        r'^delete/(?P<host_id>[0-9]+)/$',
        host_delete,
        name="host_delete"
    ),
    url(
        r'^encryption/cipher/(?P<cipher>[0-9A-Za-z-]+)$',
        EncryptionCipherDetailView.as_view(),
        name='encryption_cipher_detail'
    ),
    url(
        r'^archive/$',
        ClosedVulnerabilityView.as_view(),
        name='archive_vulnerabilities'
    ),
    url(
        r'^application/edit-title/(?P<id>[0-9]+)/$',
        ApplicationEditTitleView.as_view(),
        name='application_edit_tilte'
    ),
    url(
        r'^application/toggle-scope/(?P<id>[0-9]+)/$',
        ApplicationScopeToggleView.as_view(),
        name='application_toggle_scope'
    ),
    url(
        r'^unscanned-ports/$',
        UnscannedPortsView.as_view(),
        name='unscanned_ports'
    ),
    url(
        r'^logs/delete/$',
        MicroLogsDeleteView.as_view(),
        name='logs_delete'
    ),
    url(
        r'^charts/encryption/$',
        encryption_chart_data,
        name='encryption-chart-records'
    ),
    url(
        r'^charts/application/$',
        application_chart_data,
        name='application-chart-records'
    ),
    url(
        r'^applications/vulnerabilities/(?P<virtue_id>[0-9]+)/$',
        ApplicationVulnerabilityView.as_view(),
        name='application_vulnerabilities'
    ),
    url(
        r'^application-vulnerabilities/edit/(?P<id>[0-9]+)/$',
        ApplicationVulnerabilityUpdateView.as_view(),
        name='edit_application_vulnerabilities'
    ),
]
