from django.conf.urls import url
from . import views
from .views import (
    HomeView, DashBoardView, VulnerabilitiesView,
    HostsView, IpsInfoDetailView, DeleteHostView,
    AnaylyticsView, ApplicationsView, ReportsListView, SettingsView,
    AwsAssetsCreateListView, EncryptionView,
    NetworkVulnerabilitiesDetailView, NetworkDetailView,
    HostNetworkUpdateView, NetworkCreateListView, ApplicationView, DomainView,
    ClosedVulnerabilityView, DashboardHistoricalDataView,
    AffectedHostVulnerabilityView, UpdateScanningView,
    AnalyticsDataView, VulnerabilityDetailView, RetestVulnerabilityView,
    UpdateHostCountView, CloudAssetsDetailView,
    CloudAssetView, GetNotificationsView,
    UpdateNotificationView, NotificationsView,
    ApplicationByIdView, EncryptionProtocolDetailView, ReportDetailView,
    HostVulnerabilityDetail, EncryptionSsh, EncryptionCipher,
    EncryptionSshDetailView, HostsCreateListView,ApplicationDetailView,
    DomainDetailView, AWSKeyStatusDetailView, ApplicationVulnerabilityDetailView,
    HostEncryptionCipherDetail, VulnerabilityHostView, HostVulnerabilitiesDetailView,
    CloudDetailView, CloudAssetDetailView, UpdateApplicationScanStatusView,HostDetailView,
    HostsWhoisMapView, VulnerabilityNetworkDetailView,
    EncryptionChartView, EncryptionCipherView, EncryptionCertificateView
)

urlpatterns = [
    url(
        r'^$',
        HomeView.as_view() ,
        name='home'
    ),
    url(
        r'^dashboard/$',
        DashBoardView.as_view(),
        name='dashboard'
    ),
    url(
        r'^vulnerabilities/$',
        VulnerabilitiesView.as_view(),
        name='vulnerabilities'
    ),
    url(
        r'^hosts/$',
        HostsView.as_view(),
        name='hosts'
    ),
    url(
        r'^data/iptrackinfo/$',
        IpsInfoDetailView.as_view(),
        name="iptrackinfo"
    ),
    url(
        r'^hosts/delete/$',
        DeleteHostView.as_view(),
        name='delete_host'
    ),
    url(
        r'^analytics/$',
        AnaylyticsView.as_view(),
        name='analytics'
    ),
    url(
        r'^applications/$',
        ApplicationsView.as_view(),
        name='applications'
    ),
    url(
        r'^applications/(?P<application_id>[0-9]+)/toggle_active/$',
        UpdateApplicationScanStatusView.as_view(),
        name='update_application_scan_status'
    ),
    url(
        r'^reports/$',
        ReportsListView.as_view(),
        name='reports'
    ),
    url(
        r'^settings/$',
        SettingsView.as_view(),
        name='settings'
    ),
    url(
        r'^vulnerabilities/external/(?P<virtue_id>[0-9]+)/$',
        AffectedHostVulnerabilityView.as_view(),
        name='external_affected_hosts'
    ),
    url(
        r'^vulnerabilities/internal/(?P<virtue_id>[0-9]+)/$',
        AffectedHostVulnerabilityView.as_view(),
        name='internal_affected_hosts'
    ),
    url(
        r'^vulnerabilities/host/(?P<host_id>[0-9]+)/$',
        VulnerabilityHostView.as_view(),
        name='vulnerability_host'
    ),
    url(
        r'^vulnerabilities/host/(?P<host_id>[0-9]+)/(?P<virtue_id>[0-9]+)/$',
        HostVulnerabilitiesDetailView.as_view(),
        name='vulnerabilities_host_detail'
    ),
    url(
        r'^vulnerabilities/(?P<virtue_id>[0-9]+)/(?P<vul_id>[0-9]+)/$',
        VulnerabilityDetailView.as_view(),
        name='vulnerability_detail'
    ),
    url(
        r'^vulnerability/(?P<vul_id>[0-9]+)/$',
        HostVulnerabilityDetail.as_view(),
        name='host_vulnerability_detail'
    ),
    url(
        r'^api/retest/(?P<vul_id>[0-9]+)$',
        RetestVulnerabilityView.as_view(),
        name='affected_host_retest'
    ),
    url(
        r'^api/toggle_activity$',
        UpdateScanningView.as_view(),
        name="scanning"
    ),
    url(
        r'^api/analytics$',
        AnalyticsDataView.as_view(),
        name="analytics_api"
    ),
    url(
        r'^update-notifications$',
        UpdateNotificationView.as_view(),
        name='update_notifications'
    ),
    url(
        r'^api/notifications$',
        GetNotificationsView.as_view(),
        name='get_notifications'
    ),
    url(
        r'^hosts/applications/$',
        ApplicationView.as_view(),
        name='applications'
    ),
    url(
        r'^hosts/applications/(?P<id>[0-9]+)/$',
        ApplicationDetailView.as_view(),
        name='applications_detail'
    ),
    url(
        r'^hosts/host/$',
        HostsCreateListView.as_view(),
        name='host_create_list'
    ),
    url(
        r'^hosts/whois/$',
        HostsWhoisMapView.as_view(),
        name='host_whois_Map'
    ),
    url(
        r'^hosts/domains/$',
        DomainView.as_view(),
        name='domains_create_list'
    ),
    url(
        r'^hosts/cloud-assets/$',
        CloudAssetView.as_view(),
        name='cloud_assets'
    ),
    url(
        r'^hosts/cloud-assets/(?P<asset_id>\w+)/$',
        CloudAssetsDetailView.as_view(),
        name='cloud_assets_detail'
    ),
    url(
        r'^hosts/update-count/$',
        UpdateHostCountView.as_view(),
        name='update_host_count'
    ),
    url(
        r'^api/charts/dashboard_history$',
        DashboardHistoricalDataView.as_view(),
        name='dashboard_historical_data'
    ),
    url(
        r'^api/charts/encryption$',
        EncryptionChartView.as_view(),
        name='encryption-chart'
    ),
    url(
        r'^history/$',
        ClosedVulnerabilityView.as_view(),
        name='vulnerability_history'
    ),
    url(
        r'^error-404$',
        views.error_404,
        name='error_404'
    ),
    url(
        r'^hosts/network/$',
        NetworkCreateListView.as_view(),
        name='network-create-list'
    ),
    url(
        r'^hosts/network/(?P<network_id>[0-9]+)/$',
        NetworkDetailView.as_view(),
        name='detail_or_update_network'
    ),
    url(
        r'^host-network-update/$',
        HostNetworkUpdateView.as_view(),
        name='host_network_update'
    ),
    url(
        r'^vulnerabilities/network/(?P<network_id>[0-9]+)/$',
        NetworkVulnerabilitiesDetailView.as_view(),
        name='network_vulnerabilities_detail'
    ),
    url(
        r'^vulnerabilities/network/(?P<network_id>[0-9]+)/(?P<virtue_id>[0-9]+)/$',
        VulnerabilityNetworkDetailView.as_view(),
        name='vulnerability_network_detail'
    ),
    url(
        r'^encryption/$',
        EncryptionView.as_view(),
        name='encryption'
    ),
    url(
        r'^encryption/ciphers/$',
        EncryptionCipherView.as_view(),
        name='encryption_ciphers'
    ),
    url(
        r'^encryption/certificates/$',
        EncryptionCertificateView.as_view(),
        name='encryption_certificates'
    ),
    url(
        r'^encryption/proto/(?P<protocol>\w+)/$',
        EncryptionProtocolDetailView.as_view(),
        name='encryption_detail'
    ),
    url(
        r'^hosts/aws-assets/$',
        AwsAssetsCreateListView.as_view(),
        name='aws_assets_create_list'),
    url(
        r'^notifications/$',
        NotificationsView.as_view(),
        name='notifications'
    ),
    url(
        r'^applications/(?P<application_id>[0-9]+)/$',
        ApplicationByIdView.as_view(),
        name='applicationById'
    ),
    url(
        r'^reports/(?P<report_id>[0-9]+)/$',
        ReportDetailView.as_view(),
        name='report-detail'
    ),
    url(
        r'^encryption/ssh/$',
        EncryptionSsh.as_view(),
        name='encryption_ssh'
    ),
    url(
        r'^encryption/(?P<cipher>[0-9a-zA-Z-_]+)/$',
        EncryptionCipher.as_view(),
        name='encryption_cipher'
    ),
    url(
        r'^encryption/host/(?P<host_id>[0-9]+)/$',
        HostEncryptionCipherDetail.as_view(),
        name='host-encryption-cipher'
    ),
    url(
        r'^encryption/ssh/(?P<type>[0-9A-Za-z-_]+)/(?P<cipher>[0-9A-Za-z-.@]+)/$',
        EncryptionSshDetailView.as_view(),
        name='ssh-encryption-detail'
    ),
    url(
        r'^hosts/domains/(?P<domain_id>[0-9]+)/$',
        DomainDetailView.as_view(),
        name='detail_or_update_domains'
    ),
    url(
        r'^api/aws-key-status/(?P<id>[0-9]+)$',
        AWSKeyStatusDetailView.as_view(),
        name='aws_key_status'
    ),
    url(
        r'^applications/(?P<application_id>[0-9]+)/vulnerability/(?P<virtue_id>[0-9]+)/$',
        ApplicationVulnerabilityDetailView.as_view(),
        name='applications_detail'
    ),
    url(
        r'^cloud/$',
        CloudDetailView.as_view(),
        name="cloud"
    ),
    url(
        r'^cloud/s3/(?P<cloud_asset_id>[0-9]+)/$',
        CloudAssetDetailView.as_view(),
        name="cloud_asset_detail"
    ),
    url(
        r'^host/(?P<host_id>[0-9]+)/$',
        HostDetailView.as_view(),
        name="host_detail"
    ),
]
